name: my_fit_journey
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  async: ^2.11.0
  country_flags: ^3.0.0
  equatable: ^2.0.5
  flutter_svg: ^2.0.10+1
  image_picker: ^1.1.2
  localization: ^2.1.1
  path_provider: ^2.1.4
  photo_view: ^0.15.0
  shared_preferences: ^2.3.1
  uuid: ^4.4.2
  xml: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: ^5.13.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/i18n/
    - assets/SVG/
